SET NAMES latin1;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `recruits_college` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(90) NOT NULL,
  `slug` varchar(50) NOT NULL,
  `state` varchar(2) NOT NULL,
  `conference_id` int(11) default NULL,
  PRIMARY KEY  (`id`),
  KEY `recruits_college_slug` (`slug`),
  KEY `recruits_college_conference_id` (`conference_id`)
) ENGINE=MyISAM AUTO_INCREMENT=30076 DEFAULT CHARSET=latin1;

insert into `recruits_college` values('1083','Fort Lewis College','fort-lewis-college','',null),
 ('8577','New Mexico Highlands University','new-mexico-highlands-university','NM',null),
 ('506','Northern Michigan University','northern-michigan-university','MI',null),
 ('310','Iona College','iona-college','',null),
 ('56','Bentley College','bentley-college','',null),
 ('1068','Elon','elon','',null),
 ('21','Alma College','alma-college','',null),
 ('386','Marist College','marist-college','',null),
 ('9','UAB','uab','',null),
 ('676','Stephen F. Austin State University','stephen-f-austin-state-university','',null),
 ('441','University of Montana','university-of-montana','MT',null),
 ('691','Tennessee State University','tennessee-state-university','TN',null),
 ('8875','Chowan University','chowan-university','',null),
 ('7','Alabama State University','alabama-state-university','AL',null),
 ('445','Morehouse College','morehouse-college','',null),
 ('553','Prairie View A&amp;M University','prairie-view-aamp;m-university','',null),
 ('665','Southern University, Baton Rouge','southern-university-baton-rouge','',null),
 ('432','Mississippi Valley State University','mississippi-valley-state-university','MS',null),
 ('314','Jackson State University','jackson-state-university','',null),
 ('43','Austin Peay State University','austin-peay-state-university','',null),
 ('1395','Tarleton State University','tarleton-state-university','',null),
 ('667','Southern Utah University','southern-utah-university','UT',null),
 ('153','Colgate University','colgate-university','',null),
 ('683','Stony Brook University','stony-brook-university','',null),
 ('283','Hofstra University','hofstra-university','',null),
 ('342','Lafayette College','lafayette-college','',null),
 ('1010','Central Washington University','central-washington-university','',null),
 ('270','Hampton University','hampton-university','',null),
 ('237','Fort Valley State University','fort-valley-state-university','',null),
 ('791','Winston-Salem State University','winston-salem-state-university','',null),
 ('488','North Carolina A&amp;T State University','north-carolina-aamp;t-state-university','NC',null),
 ('61','Bethune-Cookman University','bethune-cookman-university','',null),
 ('422','Miles College','miles-college','',null),
 ('726','Navy','navy','',null),
 ('1320','Presbyterian College','presbyterian-college','',null),
 ('1462','Wingate University','wingate-university','',null),
 ('9223','North Greenville University','north-greenville-university','',null),
 ('632','Savannah State University','savannah-state-university','',null),
 ('741','Virginia Military Institute','virginia-military-institute','VA',null),
 ('251','Georgetown University','georgetown-university','',null),
 ('149','Coastal Carolina University','coastal-carolina-university','',null),
 ('649','South Dakota State University','south-dakota-state-university','',null),
 ('333','Kentucky Wesleyan College','kentucky-wesleyan-college','KY',null),
 ('189','Drake University','drake-university','',null),
 ('316','Jacksonville University','jacksonville-university','',null),
 ('489','N.C. Central','nc-central','',null),
 ('446','Morgan State University','morgan-state-university','',null),
 ('1123','Henderson State University','henderson-state-university','',null),
 ('650','University of South Dakota','university-of-south-dakota','',null),
 ('41','Augustana College (South Dakota)','augustana-college-south-dakota','SD',null),
 ('172','Dartmouth College','dartmouth-college','',null),
 ('540','University of Pennsylvania','university-of-pennsylvania','PA',null),
 ('711','Towson University','towson-university','',null),
 ('1199','Mars Hill College','mars-hill-college','',null),
 ('8411','University of Arkansas, Monticello','university-of-arkansas,-monticello','AR',null),
 ('65','Bloomsburg University of Pennslyvania','bloomsburg-university-of-pennslyvania','PA',null),
 ('1376','Southern Arkansas University','southern-arkansas-university','AR',null),
 ('36','Assumption College','assumption-college','',null),
 ('720','Tuskegee University','tuskegee-university','',null),
 ('360','Lock Haven University of Pennsylvania','lock-haven-university-of-pennsylvania','PA',null),
 ('643','Slippery Rock University of Pennsylvania','slippery-rock-university-of-pennsylvania','PA',null),
 ('743','Virginia State University','virginia-state-university','VA',null),
 ('627','University of San Diego','university-of-san-diego','',null),
 ('616','St. Paul\'s College','st-paul\'s-college','',null),
 ('80','Brown University','brown-university','',null),
 ('765','West Chester University of Pennsylvania','west-chester-university-of-pennsylvania','PA',null),
 ('83','Bucknell University','bucknell-university','PA',null),
 ('658','Southern Connecticut State University','southern-connecticut-state-university','CT',null),
 ('14','University at Albany','university-at-albany','',null),
 ('617','St. Peter\'s College','st-peter\'s-college','',null),
 ('579','Robert Morris University','robert-morris-university','',null),
 ('748','Wagner College','wagner-college','',null),
 ('590','Sacred Heart University','sacred-heart-university','',null),
 ('9081','Concordia University, St. Paul','concordia-university,-st-paul','',null),
 ('636','Shaw University','shaw-university','',null),
 ('412','Methodist University','methodist-university','',null),
 ('1403','Tiffin University','tiffin-university','',null),
 ('55','Benedict College','benedict-college','',null),
 ('347','Lane College','lane-college','',null),
 ('332','Kentucky State University','kentucky-state-university','KY',null),
 ('13','Albany State University (Georgia)','albany-state-university-georgia','GA',null),
 ('175','University of Dayton','university-of-dayton','',null),
 ('1013','University of Charleston (West Virginia)','university-of-charleston-west-virginia','WV',null),
 ('199','Texas A&amp;M University-Commerce','texas-aamp;m-university-commerce','TX',null),
 ('8744','Southwestern Oklahoma State University','southwestern-oklahoma-state-university','',null),
 ('696','Texas A&amp;M University-Kingsville','texas-aamp;m-university-kingsville','TX',null),
 ('206','Eastern New Mexico University','eastern-new-mexico-university','NM',null),
 ('2','Abilene Christian University','abilene-christian-university','TX',null),
 ('767','West Texas A&amp;M University','west-texas-aamp;m-university','TX',null),
 ('439','Monmouth University','monmouth-university','',null),
 ('554','Princeton University','princeton-university','',null),
 ('236','Fordham University','fordham-university','',null),
 ('285','College of the Holy Cross','college-of-the-holy-cross','',null),
 ('600','Saint Francis University (Pennsylvania)','saint-francis-university-pennsylvania','PA',null),
 ('813','Yale University','yale-university','',null),
 ('352','Lehigh University','lehigh-university','',null),
 ('494','University of North Dakota','university-of-north-dakota','ND',null),
 ('427','University of Minnesota Duluth','university-of-minnesota-duluth','MN',null),
 ('598','St. Cloud State University','st-cloud-state-university','',null),
 ('1446','Western Oregon University','western-oregon-university','OR',null),
 ('1448','Western Washington University','western-washington-university','',null),
 ('383','Minnesota State University, Mankato','minnesota-state-university,-mankato','MN',null),
 ('464','University of Nebraska at Omaha','university-of-nebraska-at-omaha','NE',null),
 ('144','Clark Atlanta University','clark-atlanta-university','GA',null),
 ('734','Valdosta State University','valdosta-state-university','',null),
 ('680','Stillman College','stillman-college','',null),
 ('1001','Catawba College','catawba-college','',null),
 ('594','St. Augustine\'s College','st-augustine\'s-college','',null),
 ('766','University of West Georgia','university-of-west-georgia','GA',null),
 ('223','Fayetteville State University','fayetteville-state-university','',null),
 ('1170','Lenoir-Rhyne College','lenoir-rhyne-college','',null),
 ('12830','Tusculum College','tusculum-college','',null),
 ('1257','Newberry College','newberry-college','',null),
 ('173','Davidson College','davidson-college','',null),
 ('1000','Carson-Newman College','carson-newman-college','',null),
 ('1028','Concord University','concord-university','',null),
 ('323','Johnson C. Smith University','johnson-c-smith-university','',null),
 ('158','Columbia University-Barnard College','columbia-university-barnard-college','',null),
 ('1445','Western New Mexico University','western-new-mexico-university','NM',null),
 ('1156','University of Nebraska at Kearney','university-of-nebraska-at-kearney','NE',null),
 ('11416','Mesa State College','mesa-state-college','',null),
 ('929','Adams State College','adams-state-college','',null),
 ('1012','Chadron State College','chadron-state-college','NE',null),
 ('795','University of Wisconsin, La Crosse','university-of-wisconsin,-la-crosse','',null),
 ('735','Valparaiso University','valparaiso-university','',null),
 ('435','University of Missouri, Rolla','university-of-missouri,-rolla','MO',null),
 ('87','Butler University','butler-university','IN',null),
 ('1438','West Liberty State College','west-liberty-state-college','',null),
 ('356','Lincoln University (Missouri)','lincoln-university-missouri','MO',null),
 ('30049','Central State University','central-state-university','',null),
 ('800','University of Wisconsin, Platteville','university-of-wisconsin,-platteville','',null),
 ('70','Bowie State University','bowie-state-university','MD',null),
 ('181','Delta State University','delta-state-university','',null),
 ('358','University of West Alabama','university-of-west-alabama','AL',null),
 ('947','Arkansas Tech University','arkansas-tech-university','AR',null),
 ('1289','Ouachita Baptist University','ouachita-baptist-university','',null),
 ('561','Quincy University','quincy-university','',null),
 ('1266','Northern State University','northern-state-university','',null),
 ('275','Harvard University','harvard-university','',null),
 ('167','Cornell University','cornell-university','',null),
 ('263','Greensboro College','greensboro-college','',null),
 ('1116','Harding University','harding-university','',null),
 ('487','University of North Alabama','university-of-north-alabama','AL',null),
 ('209','Edinboro University of Pennsylvania','edinboro-university-of-pennsylvania','PA',null),
 ('143','Clarion University of Pennsylvania','clarion-university-of-pennsylvania','PA',null),
 ('638','Shippensburg University of Pennsylvania','shippensburg-university-of-pennsylvania','PA',null),
 ('339','Kutztown University of Pennsylvania','kutztown-university-of-pennsylvania','PA',null),
 ('423','Millersville University of Pennsylvania','millersville-university-of-pennsylvania','PA',null),
 ('197','East Stroudsburg University of Pennsylvania','east-stroudsburg-university-of-pennsylvania','PA',null),
 ('135','Cheyney University of Pennsylvania','cheyney-university-of-pennsylvania','PA',null),
 ('362','C.W. Post Campus/Long Island University','cw-post-campus/long-island-university','',null),
 ('593','Saint Anselm College','saint-anselm-college','',null),
 ('81','Bryant University','bryant-university','',null),
 ('22','American International College','american-international-college','',null),
 ('410','Merrimack College','merrimack-college','',null),
 ('533','Pace University','pace-university','',null),
 ('384','Mansfield University of Pennsylvania','mansfield-university-of-pennsylvania','PA',null),
 ('106','California University of Pennsylvania','california-university-of-pennsylvania','PA',null),
 ('307','Indiana University of Pennsylvania','indiana-university-of-pennsylvania','IN',null),
 ('744','Virginia Union University','virginia-union-university','VA',null),
 ('210','Elizabeth City State University','elizabeth-city-state-university','',null),
 ('194','Duquesne University','duquesne-university','',null),
 ('682','Stonehill College','stonehill-college','',null),
 ('622','Salisbury University','salisbury-university','',null),
 ('340','La Salle University','la-salle-university','',null),
 ('259','Rowan University','rowan-university','',null),
 ('565','Randolph-Macon College','randolph-macon-college','',null),
 ('225','Ferrum College','ferrum-college','',null),
 ('139','Christopher Newport University','christopher-newport-university','',null),
 ('44','Averett University','averett-university','',null),
 ('604','Saint Joseph\'s College (Indiana)','saint-joseph\'s-college-indiana','IN',null),
 ('12810','Northeastern State University','northeastern-state-university','',null),
 ('155','Colorado School of Mines','colorado-school-of-mines','CO',null),
 ('2814','Washburn University of Topeka','washburn-university-of-topeka','',null),
 ('291','Humboldt State University','humboldt-state-university','',null),
 ('2759','Western State College of Colorado','western-state-college-of-colorado','CO',null),
 ('359','Livingstone College','livingstone-college','',null),
 ('9630','West Virginia Wesleyan College','west-virginia-wesleyan-college','WV',null),
 ('496','North Park University','north-park-university','',null),
 ('27854','University of Minnesota, Crookston','university-of-minnesota,-crookston','MN',null),
 ('1240','Minnesota State University Moorhead','minnesota-state-university-moorhead','MN',null),
 ('8736','Southwest Minnesota State University','southwest-minnesota-state-university','MN',null),
 ('728','Upper Iowa University','upper-iowa-university','IA',null),
 ('10870','Shepherd University','shepherd-university','',null),
 ('405','Menlo College','menlo-college','',null),
 ('134','Chapman University','chapman-university','',null),
 ('770','Western Connecticut State University','western-connecticut-state-university','CT',null),
 ('801','University of Wisconsin, River Falls','university-of-wisconsin,-river-falls','',null),
 ('54','Bemidji State University','bemidji-state-university','',null),
 ('790','Winona State University','winona-state-university','',null),
 ('491','North Carolina Wesleyan College','north-carolina-wesleyan-college','NC',null),
 ('216','Emory and Henry College','emory-and-henry-college','',null),
 ('396','Maryville College (Tennessee)','maryville-college-tennessee','TN',null),
 ('637','Shenandoah University','shenandoah-university','',null),
 ('1079','University of Findlay','university-of-findlay','',null),
 ('280','Hillsdale College','hillsdale-college','',null),
 ('246','Gannon University','gannon-university','',null),
 ('1098','Glenville State College','glenville-state-college','',null),
 ('1439','West Virginia State University','west-virginia-state-university','WV',null),
 ('1076','Fairmont State University','fairmont-state-university','',null),
 ('1222','Midwestern State University','midwestern-state-university','',null),
 ('1009','University of Central Oklahoma','university-of-central-oklahoma','',null),
 ('1371','Southeastern Oklahoma State University','southeastern-oklahoma-state-university','',null),
 ('24342','Oklahoma Panhandle State University','oklahoma-panhandle-state-university','',null),
 ('8965','East Central University','east-central-university','',null),
 ('25','Angelo State University','angelo-state-university','',null),
 ('224','Ferris State University','ferris-state-university','',null),
 ('1433','Wayne State College (Nebraska)','wayne-state-college-nebraska','NE',null),
 ('9013','Missouri Western State University','missouri-western-state-university','MO',null),
 ('785','Willamette University','willamette-university','',null),
 ('507','Northwest Missouri State University','northwest-missouri-state-university','MO',null),
 ('9011','Fort Hays State University','fort-hays-state-university','',null),
 ('130','University of Central Missouri','university-of-central-missouri','MO',null),
 ('802','University of Wisconsin, Stevens Point','university-of-wisconsin,-stevens-point','',null),
 ('805','University of Wisconsin, Whitewater','university-of-wisconsin,-whitewater','',null),
 ('803','University of Wisconsin, Stout','university-of-wisconsin,-stout','',null),
 ('798','University of Wisconsin, Oshkosh','university-of-wisconsin,-oshkosh','',null),
 ('8911','Wisconsin Lutheran College','wisconsin-lutheran-college','',null),
 ('42','Aurora University','aurora-university','',null),
 ('15','Albion College','albion-college','',null),
 ('192','University of Dubuque','university-of-dubuque','',null),
 ('40','Augustana College (Illinois)','augustana-college-illinois','IL',null),
 ('793','University of Wisconsin, Eau Claire','university-of-wisconsin,-eau-claire','',null),
 ('1314','Pittsburg State University','pittsburg-state-university','',null),
 ('9012','Missouri Southern State University','missouri-southern-state-university','MO',null),
 ('1112','Guilford College','guilford-college','',null),
 ('2755','Southwest Baptist University','southwest-baptist-university','',null),
 ('548','Plymouth State University','plymouth-state-university','',null),
 ('26107','Becker College','becker-college','',null),
 ('656','University of Massachusetts, Dartmouth','university-of-massachusetts,-dartmouth','MA',null),
 ('442','Montclair State University','montclair-state-university','',null),
 ('763','Wesley College','wesley-college','',null),
 ('243','Frostburg State University','frostburg-state-university','',null),
 ('730','Ursinus College','ursinus-college','',null),
 ('124','Catholic University','catholic-university','',null),
 ('712','The College of New Jersey','the-college-of-new-jersey','NJ',null),
 ('168','State University College at Cortland','state-university-college-at-cortland','',null),
 ('78','State University College at Brockport','state-university-college-at-brockport','',null),
 ('787','William Paterson University of New Jersey','william-paterson-university-of-new-jersey','NJ',null),
 ('30075','University of Mary','university-of-mary','',null),
 ('499','Truman State University','truman-state-university','',null),
 ('1133','Husson College','husson-college','',null),
 ('751','Washington and Jefferson College','washington-and-jefferson-college','',null),
 ('85','Buffalo State College','buffalo-state-college','',null),
 ('182','Denison University','denison-university','',null),
 ('752','Washington and Lee University','washington-and-lee-university','',null),
 ('773','McDaniel College','mcdaniel-college','',null),
 ('269','Hampden-Sydney College','hampden-sydney-college','',null),
 ('452','Mount Union College','mount-union-college','',null),
 ('262','Grand Valley State University','grand-valley-state-university','',null),
 ('309','University of Indianapolis','university-of-indianapolis','IN',null),
 ('296','Benedictine University (Illinois)','benedictine-university-illinois','IL',null),
 ('585','Rose-Hulman Institute of Technology','rose-hulman-institute-of-technology','',null),
 ('492','North Central College','north-central-college','',null),
 ('424','Millikin University','millikin-university','',null),
 ('778','Wheaton College (Illinois)','wheaton-college-illinois','IL',null),
 ('300','Illinois Wesleyan University','illinois-wesleyan-university','IL',null),
 ('212','Elmhurst College','elmhurst-college','',null),
 ('161','Concordia College, Moorhead','concordia-college,-moorhead','',null),
 ('8530','McMurry University','mcmurry-university','',null),
 ('22235','Lewis &amp; Clark College','lewis-amp;-clark-college','',null),
 ('1454','Whitworth University','whitworth-university','',null),
 ('1179','Linfield College','linfield-college','',null),
 ('376','Macalester College','macalester-college','',null),
 ('567','University of Redlands','university-of-redlands','',null),
 ('142','Claremont McKenna-Harvey Mudd-Scripps Colleges','claremont-mckenna-harvey-mudd-scripps-colleges','',null),
 ('781','Whittier College','whittier-college','',null),
 ('549','Pomona-Pitzer Colleges','pomona-pitzer-colleges','',null),
 ('516','Occidental College','occidental-college','',null),
 ('341','University of La Verne','university-of-la-verne','',null),
 ('602','St. John\'s University (Minnesota)','st-john\'s-university-minnesota','MN',null),
 ('385','Marietta College','marietta-college','',null),
 ('75','Bridgewater College (Virginia)','bridgewater-college-virginia','VA',null),
 ('1162','La Grange College','la-grange-college','',null),
 ('652','University of the South','university-of-the-south','',null),
 ('1434','Waynesburg College','waynesburg-college','',null),
 ('510','Northwood University (Michigan)','northwood-university-michigan','MI',null),
 ('757','Wayne State University (Michigan)','wayne-state-university-michigan','MI',null),
 ('408','Mercyhurst College','mercyhurst-college','',null),
 ('417','Michigan Technological University','michigan-technological-university','MI',null),
 ('166','Cornell College','cornell-college','',null),
 ('806','Wittenberg University','wittenberg-university','',null),
 ('30037','Tri-State University','tri-state-university','',null),
 ('286','Hope College','hope-college','',null),
 ('525','Olivet College','olivet-college','',null),
 ('4','Adrian College','adrian-college','',null),
 ('35','Ashland University','ashland-university','',null),
 ('591','Saginaw Valley State University','saginaw-valley-state-university','',null),
 ('1071','Emporia State University','emporia-state-university','',null),
 ('105','California Lutheran University','california-lutheran-university','CA',null),
 ('1297','Pacific Lutheran University','pacific-lutheran-university','',null),
 ('271','Hardin-Simmons University','hardin-simmons-university','',null),
 ('1164','Lakeland College','lakeland-college','',null),
 ('577','Ripon College','ripon-college','',null),
 ('1036','Concordia University (Wisconsin)','concordia-university-wisconsin','',null),
 ('326','Kalamazoo College','kalamazoo-college','',null),
 ('582','Rockford College','rockford-college','',null),
 ('377','MacMurray College','macmurray-college','',null),
 ('1111','Greenville College','greenville-college','',null),
 ('160','Concordia University (Illinois)','concordia-university-illinois','IL',null),
 ('218','Eureka College','eureka-college','',null),
 ('707','Thiel College','thiel-college','',null),
 ('364','Loras College','loras-college','',null),
 ('372','Luther College','luther-college','',null),
 ('126','Central College (Iowa)','central-college-iowa','IA',null),
 ('641','Simpson College','simpson-college','',null),
 ('750','Wartburg College','wartburg-college','',null),
 ('121','Carthage College','carthage-college','',null),
 ('27901','Mount Ida College','mount-ida-college','',null),
 ('775','Western New England College','western-new-england-college','',null),
 ('8981','Endicott College','endicott-college','',null),
 ('170','Curry College','curry-college','',null),
 ('398','Massachusetts Institute of Technology','massachusetts-institute-of-technology','MA',null),
 ('623','Salve Regina University','salve-regina-university','',null),
 ('733','Utica College','utica-college','',null),
 ('808','Worcester Polytechnic Institute','worcester-polytechnic-institute','',null),
 ('570','Rensselaer Polytechnic Institute','rensselaer-polytechnic-institute','',null),
 ('273','Hartwick College','hartwick-college','',null),
 ('478','State University of New York Maritime College','state-university-of-new-york-maritime-college','NY',null),
 ('76','Bridgewater State College','bridgewater-state-college','',null),
 ('484','Nichols College','nichols-college','',null),
 ('1130','Huntingdon College','huntingdon-college','',null),
 ('1402','Thomas More College','thomas-more-college','',null),
 ('1451','Westminster College (Pennsylvania)','westminster-college-pennsylvania','PA',null),
 ('685','Susquehanna University','susquehanna-university','',null),
 ('122','Case Western Reserve University','case-western-reserve-university','',null),
 ('258','Gettysburg College','gettysburg-college','',null),
 ('322','Johns Hopkins University','johns-hopkins-university','',null),
 ('185','Dickinson College','dickinson-college','',null),
 ('453','Muhlenberg College','muhlenberg-college','',null),
 ('221','Fairleigh Dickinson University, Florham','fairleigh-dickinson-university,-florham','',null),
 ('329','Kean University','kean-university','',null),
 ('313','Ithaca College','ithaca-college','',null),
 ('601','St. John Fisher College','st-john-fisher-college','',null),
 ('784','Wilkes University','wilkes-university','',null),
 ('282','Hobart College','hobart-college','',null),
 ('1115','Hanover College','hanover-college','',null),
 ('426','Millsaps College','millsaps-college','',null),
 ('1062','East Texas Baptist University','east-texas-baptist-university','TX',null),
 ('783','Widener University','widener-university','',null),
 ('1203','University of Mary Hardin-Baylor','university-of-mary-hardin-baylor','',null),
 ('557','University of Puget Sound','university-of-puget-sound','',null),
 ('132','Centre College','centre-college','',null),
 ('266','Gustavus Adolphus College','gustavus-adolphus-college','',null),
 ('150','Coe College','coe-college','',null),
 ('84','Buena Vista University','buena-vista-university','',null),
 ('46','Baldwin-Wallace College','baldwin-wallace-college','',null),
 ('722','U.S. Coast Guard Academy','us-coast-guard-academy','',null),
 ('378','Maine Maritime Academy','maine-maritime-academy','ME',null),
 ('245','Gallaudet University','gallaudet-university','',null),
 ('227','Fitchburg State College','fitchburg-state-college','',null),
 ('673','Springfield College','springfield-college','',null),
 ('16','Albright College','albright-college','',null),
 ('239','Franklin &amp; Marshall College','franklin-amp;-marshall-college','',null),
 ('520','Ohio Wesleyan University','ohio-wesleyan-university','OH',null),
 ('511','Norwich University','norwich-university','',null),
 ('18','Alfred University','alfred-university','',null),
 ('19','Allegheny College','allegheny-college','PA',null),
 ('515','Oberlin College','oberlin-college','',null),
 ('265','Grove City College','grove-city-college','',null),
 ('59','Bethany College (West Virginia)','bethany-college-west-virginia','WV',null),
 ('281','Hiram College','hiram-college','',null),
 ('335','Kenyon College','kenyon-college','',null),
 ('747','Wabash College','wabash-college','',null),
 ('195','Earlham College','earlham-college','',null),
 ('531','Otterbein College','otterbein-college','',null),
 ('455','Muskingum College','muskingum-college','',null),
 ('278','Heidelberg College','heidelberg-college','',null),
 ('517','Ohio Northern University','ohio-northern-university','OH',null),
 ('1461','Wilmington College (Ohio)','wilmington-college-ohio','OH',null),
 ('117','Capital University','capital-university','',null),
 ('320','John Carroll University','john-carroll-university','',null),
 ('8567','College of Mount St. Joseph','college-of-mount-st-joseph','',null),
 ('1050','Defiance College','defiance-college','',null),
 ('987','Bluffton University','bluffton-university','',null),
 ('2694','Franklin College','franklin-college','',null),
 ('939','Anderson University (Indiana)','anderson-university-indiana','IN',null),
 ('1192','Manchester College','manchester-college','',null),
 ('755','Washington University (Missouri)','washington-university-missouri','MO',null),
 ('297','Illinois College','illinois-college','IL',null),
 ('137','University of Chicago','university-of-chicago','',null),
 ('60','Bethel University (Minnesota)','bethel-university-minnesota','MN',null),
 ('38','Augsburg College','augsburg-college','',null),
 ('268','Hamline University','hamline-university','',null),
 ('615','St. Olaf College','st-olaf-college','',null),
 ('620','University of St. Thomas (Minnesota)','university-of-st-thomas-minnesota','MN',null),
 ('118','Carleton College','carleton-college','',null),
 ('1226','University of Minnesota, Morris','university-of-minnesota,-morris','MN',null),
 ('953','Austin College','austin-college','',null),
 ('1182','Louisiana College','louisiana-college','LA',null),
 ('429','Mississippi College','mississippi-college','MS',null),
 ('2741','Howard Payne University','howard-payne-university','',null),
 ('1390','Sul Ross State University','sul-ross-state-university','',null),
 ('1400','Texas Lutheran University','texas-lutheran-university','TX',null),
 ('154','Colorado College','colorado-college','CO',null),
 ('53','Beloit College','beloit-college','',null),
 ('555','Principia College','principia-college','',null),
 ('30035','Crown College (MN)','crown-college-mn','',null),
 ('715','Trinity University (Texas)','trinity-university-texas','TX',null),
 ('177','DePauw University','depauw-university','',null),
 ('573','Rhodes College','rhodes-college','',null),
 ('807','College of Wooster','college-of-wooster','',null),
 ('30031','Northwestern College','northwestern-college','',null),
 ('344','Lake Forest College','lake-forest-college','',null),
 ('337','Knox College','knox-college','',null),
 ('120','Carroll College (Wisconsin)','carroll-college-wisconsin','',null),
 ('438','Monmouth College (Illinois)','monmouth-college-illinois','IL',null),
 ('614','St. Norbert College','st-norbert-college','',null),
 ('264','Grinnell College','grinnell-college','',null),
 ('348','Lawrence University','lawrence-university','',null),
 ('1194','Maranatha Baptist Bible College','maranatha-baptist-bible-college','',null),
 ('1450','Westminster College (Missouri)','westminster-college-missouri','MO',null),
 ('64','Blackburn College','blackburn-college','',null),
 ('8597','Martin Luther College','martin-luther-college','',null),
 ('119','Carnegie Mellon University','carnegie-mellon-university','',null),
 ('777','Westfield State College','westfield-state-college','',null),
 ('399','Massachusetts Maritime Academy','massachusetts-maritime-academy','MA',null),
 ('809','Worcester State College','worcester-state-college','',null),
 ('238','Framingham State College','framingham-state-college','',null),
 ('724','U.S. Merchant Marine Academy','us-merchant-marine-academy','',null),
 ('727','Union College (New York)','union-college-new-york','NY',null),
 ('581','University of Rochester','university-of-rochester','',null),
 ('607','St. Lawrence University','st-lawrence-university','',null),
 ('443','Moravian College','moravian-college','',null),
 ('336','King\'s College (Pennsylvania)','king\'s-college-pennsylvania','PA',null),
 ('325','Juniata College','juniata-college','',null),
 ('179','Delaware Valley College','delaware-valley-college','DE',null),
 ('373','Lycoming College','lycoming-college','',null),
 ('351','Lebanon Valley College','lebanon-valley-college','',null),
 ('5','Akron','akron','OH',null),
 ('30','Arkansas St.','arkansas-st','AR',null),
 ('47','Ball St.','ball-st','IN',null),
 ('66','Boise St.','boise-st','ID','8'),
 ('71','Bowling Green','bowling-green','OH',null),
 ('77','Brigham Young','brigham-young','UT','8'),
 ('86','Buffalo','buffalo','',null),
 ('96','Fresno St.','fresno-st','',null),
 ('128','UCF','ucf','',null),
 ('156','Colorado St.','colorado-st','CO',null),
 ('204','Eastern Mich.','eastern-mich','',null),
 ('277','Hawaii','hawaii','HI',null),
 ('288','Houston','houston','',null),
 ('295','Idaho','idaho','ID',null),
 ('331','Kent St.','kent-st','',null),
 ('366','Louisiana Tech','louisiana-tech','LA',null),
 ('388','Marshall','marshall','',null),
 ('404','Memphis','memphis','',null),
 ('414','Miami (Ohio)','miami-ohio','OH',null),
 ('419','Middle Tenn. St.','middle-tenn-st','',null),
 ('463','Nebraska','nebraska','NE',null),
 ('465','UNLV','unlv','',null),
 ('466','Nevada','nevada','NV',null),
 ('472','New Mexico St.','new-mexico-st','NM',null),
 ('473','New Mexico','new-mexico','NM',null),
 ('497','North Texas','north-texas','TX',null),
 ('498','La.-Monroe','la-monroe','',null),
 ('503','Northern Ill.','northern-ill','',null),
 ('513','Notre Dame','notre-dame','',null),
 ('519','Ohio','ohio','OH',null),
 ('626','San Diego St.','san-diego-st','',null),
 ('630','San Jose St.','san-jose-st','',null),
 ('663','Southern Methodist','southern-methodist','',null),
 ('664','Southern Miss.','southern-miss','',null),
 ('671','La.-Lafayette','la-lafayette','',null),
 ('690','Temple','temple','',null),
 ('698','TCU','tcu','',null),
 ('700','Texas Tech','texas-tech','TX',null),
 ('704','UTEP','utep','',null),
 ('709','Toledo','toledo','',null),
 ('716','Troy','troy','',null),
 ('718','Tulane','tulane','',null),
 ('719','Tulsa','tulsa','',null),
 ('721','Air Force','air-force','CO',null),
 ('725','Army','army','NY',null),
 ('731','Utah St.','utah-st','UT',null),
 ('732','Utah','utah','UT',null),
 ('772','Western Ky.','western-ky','',null),
 ('774','Western Mich.','western-mich','',null),
 ('811','Wyoming','wyoming','WY',null),
 ('769','Western Caro.','western-caro','',null),
 ('17','Alcorn St.','alcorn-st','',null),
 ('501','Northern Ariz.','northern-ariz','',null),
 ('693','Chattanooga','chattanooga','TN',null),
 ('692','Tennessee Tech','tennessee-tech','TN',null),
 ('670','Texas St.','texas-st','TX',null),
 ('758','Weber St.','weber-st','',null),
 ('400','Massachusetts','massachusetts','MA',null),
 ('207','Eastern Wash.','eastern-wash','',null),
 ('102','Sacramento St.','sacramento-st','',null),
 ('493','North Dakota St.','north-dakota-st','ND',null),
 ('654','Southeast Mo. St.','southeast-mo-st','',null),
 ('244','Furman','furman','',null),
 ('253','Ga. Southern','ga-southern','',null),
 ('380','Maine','maine','ME',null),
 ('290','Howard','howard','',null),
 ('625','Samford','samford','',null),
 ('502','Northern Colo.','northern-colo','',null),
 ('699','Texas Southern','texas-southern','TX',null),
 ('90','Cal Poly','cal-poly','',null),
 ('771','Western Ill.','western-ill','',null),
 ('305','Indiana St.','indiana-st','IN',null),
 ('504','Northern Iowa','northern-iowa','IA',null),
 ('669','Missouri St.','missouri-st','MO',null),
 ('655','Southeastern La.','southeastern-la','',null),
 ('178','Delaware St.','delaware-st','DE',null),
 ('202','Eastern Ky.','eastern-ky','',null),
 ('454','Murray St.','murray-st','',null),
 ('469','New Hampshire','new-hampshire','NH',null),
 ('739','Villanova','villanova','',null),
 ('315','Jacksonville St.','jacksonville-st','',null),
 ('27','Appalachian St.','appalachian-st','NC',null),
 ('1092','Gardner-Webb','gardner-webb','',null),
 ('508','Northwestern St.','northwestern-st','',null),
 ('299','Illinois St.','illinois-st','IL',null),
 ('317','James Madison','james-madison','',null),
 ('483','Nicholls St.','nicholls-st','',null),
 ('2915','Wofford','wofford','',null),
 ('261','Grambling','grambling','',null),
 ('659','Southern Ill.','southern-ill','',null),
 ('500','Northeastern','northeastern','',null),
 ('817','Youngstown St.','youngstown-st','',null),
 ('624','Sam Houston St.','sam-houston-st','',null),
 ('294','Idaho St.','idaho-st','ID',null),
 ('201','Eastern Illinois','eastern-illinois','IL',null),
 ('485','Norfolk St.','norfolk-st','',null),
 ('550','Portland St.','portland-st','',null),
 ('108','UC Davis','uc-davis','',null),
 ('647','South Carolina St.','south-carolina-st','SC',null),
 ('695','Tenn.-Martin','tenn-martin','',null),
 ('402','McNeese St.','mcneese-st','',null),
 ('440','Montana St.','montana-st','MT',null),
 ('355','Liberty','liberty','',null),
 ('572','Rhode Island','rhode-island','RI',null),
 ('180','Delaware','delaware','DE',null),
 ('575','Richmond','richmond','',null),
 ('786','William & Mary','william--mary','',null),
 ('444','Morehead St.','morehead-st','',null),
 ('14901','West Va. Tech','west-va-tech','',null),
 ('127','Central Conn. St.','central-conn-st','',null),
 ('141','Citadel','citadel','',null),
 ('8','Alabama','alabama','AL','1'),
 ('29','Arizona','arizona','AZ','4'),
 ('28','Arizona St.','arizona-st','AZ','4'),
 ('37','Auburn','auburn','AL','1'),
 ('31','Arkansas','arkansas','AR','1'),
 ('51','Baylor','baylor','TX','7'),
 ('67','Boston College','boston-college','MA','2'),
 ('107','California','california','CA',null),
 ('140','Cincinnati','cincinnati','OH','3'),
 ('147','Clemson','clemson','SC','2'),
 ('157','Colorado','colorado','CO','7'),
 ('164','Connecticut','connecticut','CT',null),
 ('193','Duke','duke','',null),
 ('235','Florida','florida','FL',null),
 ('234','Florida St.','florida-st','FL',null),
 ('257','Georgia','georgia','GA',null),
 ('255','Georgia Tech','georgia-tech','GA',null),
 ('301','Illinois','illinois','IL',null),
 ('306','Indiana','indiana','IN',null),
 ('312','Iowa','iowa','IA',null),
 ('311','Iowa St.','iowa-st','IA',null),
 ('328','Kansas','kansas','',null),
 ('327','Kansas St.','kansas-st','',null),
 ('334','Kentucky','kentucky','KY',null),
 ('365','LSU','lsu','',null),
 ('367','Louisville','louisville','',null),
 ('392','Maryland','maryland','',null),
 ('415','Miami (Fla.)','miami-fla','',null),
 ('418','Michigan','michigan','MI',null),
 ('416','Michigan St.','michigan-st','MI',null),
 ('428','Minnesota','minnesota','MN',null),
 ('433','Mississippi','mississippi','MS',null),
 ('430','Mississippi St.','mississippi-st','MS',null),
 ('434','Missouri','missouri','MO',null),
 ('457','North Carolina','north-carolina','NC',null),
 ('490','North Carolina St.','north-carolina-st','NC',null),
 ('509','Northwestern','northwestern','',null),
 ('518','Ohio St.','ohio-st','OH',null),
 ('522','Oklahoma','oklahoma','',null),
 ('521','Oklahoma St.','oklahoma-st','',null),
 ('529','Oregon','oregon','OR',null),
 ('528','Oregon St.','oregon-st','OR',null),
 ('539','Penn St.','penn-st','',null),
 ('545','Pittsburgh','pittsburgh','',null),
 ('559','Purdue','purdue','',null),
 ('574','Rice','rice','',null),
 ('587','Rutgers','rutgers','',null),
 ('648','South Carolina','south-carolina','SC',null),
 ('651','South Fla.','south-fla','',null),
 ('657','Southern California','southern-california','CA',null),
 ('674','Stanford','stanford','',null),
 ('688','Syracuse','syracuse','',null),
 ('694','Tennessee','tennessee','TN',null),
 ('703','Texas','texas','TX',null),
 ('697','Texas A&M','texas-am','TX',null),
 ('110','UCLA','ucla','',null),
 ('736','Vanderbilt','vanderbilt','',null),
 ('746','Virginia','virginia','VA',null),
 ('742','Virginia Tech','virginia-tech','VA',null),
 ('749','Wake Forest','wake-forest','',null),
 ('756','Washington','washington','',null),
 ('754','Washington St.','washington-st','',null),
 ('768','West Virginia','west-virginia','WV',null),
 ('796','Wisconsin','wisconsin','',null),
 ('6','Alabama A&M University','alabama-am-university','AL',null),
 ('2678','Arkansas-Pine Bluff','ark-pine-bluff','AR',null),
 ('1004','Central Arkansas','central-arkansas','AR',null),
 ('129','Central Michigan','central-michigan','MI',null),
 ('48','Charleston Southern','charleston-southern','',null),
 ('228','Florida A&M University','florida-am-university','FL',null),
 ('231','Florida International','florida-international','FL',null),
 ('196','East Carolina','east-carolina','',null),
 ('229','Florida Atlantic','florida-atlantic','FL',null);

SET FOREIGN_KEY_CHECKS = 1;