from django.conf.urls.defaults import *

urlpatterns = patterns('fumblerooski.college.views',
     url(r'^college/seasons/(?P<season>\d+)/week/(?P<week>\d+)/$', 'season_week'),
     url(r'^college/conferences/$', 'conference_index'),
     url(r'^college/conferences/(?P<conf>[-a-z0-9]+)/(?P<season>\d+)/$', 'conference_detail'),
     url(r'^college/games/$', 'game_index'),
     url(r'^college/coaches/(?P<coach>[-a-z]+)/$', 'coach_detail'),
     url(r'^college/teams/$', 'team_index'),
     url(r'^college/teams/undefeated/(?P<season>\d+)/$', 'undefeated_teams'),
     url(r'^college/teams/(?P<team>[-a-z]+)/$', 'team_detail'),
     url(r'^college/teams/(?P<team>[-a-z]+)/offense/$', 'team_offense'),
     url(r'^college/teams/(?P<team>[-a-z]+)/offense/rushing/$', 'team_offense_rushing'),
     url(r'^college/teams/(?P<team>[-a-z]+)/defense/$', 'team_defense'),
     url(r'^college/teams/(?P<team>[-a-z]+)/penalties/$', 'team_penalties'),
     url(r'^college/teams/(?P<team>[-a-z]+)/first-downs/$', 'team_first_downs'),     
     url(r'^college/teams/(?P<team>[-a-z]+)/first-downs/(?P<category>rushing|passing|penalty)/$', 'team_first_downs_category'),
#     url(r'^college/teams/(?P<team>[-a-z]+)/positions/(?<pos>[a-z][a-z][a-z]?)/$', 'team_position_detail'),
     url(r'^college/teams/(?P<team>[-a-z]+)/(?P<season>\d+)/$', 'team_detail_season'),
     url(r'^college/teams/(?P<team>[-a-z]+)/(?P<season>\d+)/rankings/$', 'team_rankings_season'),
     url(r'^college/teams/(?P<team>[-a-z]+)/(?P<season>\d+)/classes/(?P<cl>[fr|so|jr|sr])/$', 'team_by_cls'),
     url(r'^college/teams/(?P<team>[-a-z]+)/opponents/$', 'team_opponents'),
     url(r'^college/teams/(?P<team>[-a-z]+)/(?P<season>\d+)/players/$', 'team_players'),
     url(r'^college/teams/(?P<team>[-a-z]+)/(?P<season>\d+)/players/(?P<player>[-a-z]+)/$', 'player_detail'),
     url(r'^college/teams/(?P<team1>[-a-z]+)/vs/(?P<team2>[-a-z]+)/$', 'team_vs'),
     url(r'^college/teams/(?P<team1>[-a-z]+)/vs/(?P<team2>[-a-z]+)/(?P<outcome>wins|losses|ties)/$', 'team_vs'),
     url(r'^college/teams/(?P<team1>[-a-z]+)/vs/(?P<team2>[-a-z]+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', 'game'),
     url(r'^college/teams/(?P<team1>[-a-z]+)/vs/(?P<team2>[-a-z]+)/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/drives/$', 'game_drive'),     
     url(r'^states/$', 'state_index'),
     url(r'^states/(?P<state>[a-z][a-z])/$', 'state_detail'),
)