SET NAMES latin1;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `college_college` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(90) NOT NULL,
  `slug` varchar(50) NOT NULL,
  `conference_id` int(11) DEFAULT NULL,
  `state_id` varchar(2) DEFAULT NULL,
  `official_url` varchar(120) DEFAULT NULL,
  `official_rss` varchar(120) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `college_college_slug` (`slug`),
  KEY `college_college_conference_id` (`conference_id`)
) ENGINE=MyISAM AUTO_INCREMENT=30104 DEFAULT CHARSET=latin1;

insert into `college_college` values('1083','Fort Lewis College','fort-lewis-college',null,'',null,null),
 ('8577','New Mexico Highlands ','new-mexico-highlands',null,'NM',null,null),
 ('506','Northern Michigan ','northern-michigan',null,'MI',null,null),
 ('310','Iona College','iona-college',null,'NY',null,null),
 ('56','Bentley College','bentley-college',null,'',null,null),
 ('1068','Elon ','elon',null,null,null,null),
 ('21','Alma College','alma-college',null,'',null,null),
 ('386','Marist College','marist-college',null,'NY',null,null),
 ('9','Alabama-Birmingham','uab','6','AL',null,null),
 ('676','Stephen F. Austin','stephen-f-austin',null,'TX',null,null),
 ('441','Montana','montana',null,'MT',null,null),
 ('691','Tennessee State ','tennessee-state',null,'TN',null,null),
 ('8875','Chowan ','chowan',null,'',null,null),
 ('7','Alabama State ','alabama-state',null,'AL',null,null),
 ('445','Morehouse College','morehouse-college',null,'GA',null,null),
 ('553','Prairie View A&amp;M ','prairie-view-am',null,'',null,null),
 ('665','Southern','southern',null,'LA',null,null),
 ('432','Mississippi Valley State ','mississippi-valley-state',null,'MS',null,null),
 ('314','Jackson State ','jackson-state',null,'',null,null),
 ('43','Austin Peay ','austin-peay',null,'',null,null),
 ('1395','Tarleton State ','tarleton-state',null,'',null,null),
 ('667','Southern Utah ','southern-utah',null,'UT',null,null),
 ('153','Colgate ','colgate',null,'NY',null,null),
 ('683','Stony Brook ','stony-brook',null,'NY',null,null),
 ('283','Hofstra ','hofstra',null,'NY',null,null),
 ('342','Lafayette','lafayette-college',null,'PA',null,null),
 ('1010','Central Washington ','central-washington',null,'WA',null,null),
 ('270','Hampton ','hampton',null,'',null,null),
 ('237','Fort Valley State ','fort-valley-state',null,'',null,null),
 ('791','Winston-Salem State ','winston-salem-state',null,'NC',null,null),
 ('488','North Carolina A&T','north-carolina-at',null,'NC','',''),
 ('61','Bethune-Cookman ','bethune-cookman',null,'FL',null,null),
 ('422','Miles College','miles-college',null,'',null,null),
 ('726','Navy','navy','12','MD',null,null),
 ('1320','Presbyterian College','presbyterian-college',null,'',null,null),
 ('1462','Wingate ','wingate',null,'',null,null),
 ('9223','North Greenville ','north-greenville',null,'',null,null),
 ('632','Savannah State ','savannah-state',null,'GA',null,null),
 ('741','Virginia Military Institute','virginia-military-institute',null,'VA',null,null),
 ('251','Georgetown ','georgetown',null,'DC',null,null),
 ('149','Coastal Carolina ','coastal-carolina',null,'SC',null,null),
 ('649','South Dakota State ','south-dakota-state',null,'SD',null,null),
 ('333','Kentucky Wesleyan College','kentucky-wesleyan-college',null,'KY',null,null),
 ('189','Drake ','drake',null,'IA',null,null),
 ('316','Jacksonville ','jacksonville',null,'FL',null,null),
 ('489','North Carolina Central ','north-carolina-central',null,'NC',null,null),
 ('446','Morgan State ','morgan-state',null,'MD',null,null),
 ('1123','Henderson State ','henderson-state',null,'',null,null),
 ('650','South Dakota','south-dakota',null,'SD',null,null),
 ('41','Augustana College (South Dakota)','augustana-college-south-dakota',null,'SD',null,null),
 ('172','Dartmouth College','dartmouth-college',null,'NH',null,null),
 ('540','Pennsylvania','university-of-pennsylvania',null,'PA',null,null),
 ('711','Towson ','towson',null,'MD',null,null),
 ('1199','Mars Hill College','mars-hill-college',null,'',null,null),
 ('8411','Arkansas-Monticello','arkansas-monticello',null,'AR',null,null),
 ('65','Bloomsburg Pennslyvania','bloomsburg',null,'PA',null,null),
 ('1376','Southern Arkansas ','southern-arkansas',null,'AR',null,null),
 ('36','Assumption College','assumption-college',null,'',null,null),
 ('720','Tuskegee ','tuskegee',null,'AL',null,null),
 ('360','Lock Haven','lock-haven-of-pennsylvania',null,'PA',null,null),
 ('643','Slippery Rock Pennsylvania','slippery-rock-of-pennsylvania',null,'PA',null,null),
 ('743','Virginia State ','virginia-state',null,'VA',null,null),
 ('627','San Diego','san-diego',null,'CA',null,null),
 ('616','St. Paul\'s College','st-pauls-college',null,'',null,null),
 ('80','Brown ','brown',null,'RI',null,null),
 ('765','West Chester Pennsylvania','west-chester-of-pennsylvania',null,'PA',null,null),
 ('83','Bucknell ','bucknell',null,'PA',null,null),
 ('658','Southern Connecticut State ','southern-connecticut-state',null,'CT',null,null),
 ('14','Albany','university-at-albany',null,'NY',null,null),
 ('617','St. Peter\'s College','st-peters-college',null,'',null,null),
 ('579','Robert Morris ','robert-morris',null,'PA',null,null),
 ('748','Wagner College','wagner-college',null,'',null,null),
 ('590','Sacred Heart ','sacred-heart',null,'',null,null),
 ('9081','Concordia , St. Paul','concordia-st-paul',null,'MN',null,null),
 ('636','Shaw ','shaw',null,'',null,null),
 ('412','Methodist ','methodist',null,'',null,null),
 ('1403','Tiffin ','tiffin',null,'',null,null),
 ('55','Benedict College','benedict-college',null,'',null,null),
 ('347','Lane College','lane-college',null,'',null,null),
 ('332','Kentucky State ','kentucky-state',null,'KY',null,null),
 ('13','Albany State','albany-state',null,'GA',null,null),
 ('175','Dayton','dayton',null,'OH',null,null),
 ('1013','Charleston (West Virginia)','university-of-charleston-west-virginia',null,'WV',null,null),
 ('199','Texas A&amp;M -Commerce','texas-am-commerce',null,'TX',null,null),
 ('8744','Southwestern Oklahoma State ','southwestern-oklahoma-state',null,'OK',null,null),
 ('696','Texas A&amp;M -Kingsville','texas-am-kingsville',null,'TX',null,null),
 ('206','Eastern New Mexico ','eastern-new-mexico',null,'NM',null,null),
 ('2','Abilene Christian ','abilene-christian',null,'TX',null,null),
 ('767','West Texas A&amp;M ','west-texas-am',null,'TX',null,null),
 ('439','Monmouth ','monmouth',null,'NJ',null,null),
 ('554','Princeton ','princeton',null,'NJ',null,null),
 ('236','Fordham ','fordham',null,'',null,null),
 ('285','Holy Cross','college-of-the-holy-cross',null,'RI',null,null),
 ('600','Saint Francis  (Pennsylvania)','saint-francis-pennsylvania',null,'PA',null,null),
 ('813','Yale ','yale',null,'CT',null,null),
 ('352','Lehigh ','lehigh',null,'PA',null,null),
 ('494','North Dakota','north-dakota',null,'ND',null,null),
 ('427','Minnesota Duluth','minnesota-duluth',null,'MN',null,null),
 ('598','St. Cloud State ','st-cloud-state',null,'',null,null),
 ('1446','Western Oregon ','western-oregon',null,'OR',null,null),
 ('1448','Western Washington ','western-washington',null,'WA',null,null),
 ('383','Mankato State','mankato-state',null,'MN','',''),
 ('464','Nebraska at Omaha','nebraska-omaha',null,'NE',null,null),
 ('144','Clark Atlanta ','clark-atlanta',null,'GA',null,null),
 ('734','Valdosta State ','valdosta-state',null,'GA',null,null),
 ('680','Stillman College','stillman-college',null,'',null,null),
 ('1001','Catawba College','catawba-college',null,'',null,null),
 ('594','St. Augustine\'s College','st-augustines-college',null,'',null,null),
 ('766','West Georgia','west-georgia',null,'GA',null,null),
 ('223','Fayetteville State ','fayetteville-state',null,'',null,null),
 ('1170','Lenoir-Rhyne College','lenoir-rhyne-college',null,'NC',null,null),
 ('12830','Tusculum College','tusculum-college',null,'',null,null),
 ('1257','Newberry College','newberry-college',null,'',null,null),
 ('173','Davidson College','davidson',null,'NC',null,null),
 ('1000','Carson-Newman College','carson-newman-college',null,'',null,null),
 ('1028','Concord ','concord',null,'',null,null),
 ('323','Johnson C. Smith ','johnson-c-smith',null,'',null,null),
 ('158','Columbia -Barnard College','columbia',null,'NY',null,null),
 ('1445','Western New Mexico ','western-new-mexico',null,'NM',null,null),
 ('1156','Nebraska at Kearney','nebraska-kearney',null,'NE',null,null),
 ('11416','Mesa State College','mesa-state-college',null,'',null,null),
 ('929','Adams State College','adams-state-college',null,'',null,null),
 ('1012','Chadron State College','chadron-state-college',null,'NE',null,null),
 ('795','Wisconsin, La Crosse','wisconsin-la-crosse',null,'WI',null,null),
 ('735','Valparaiso ','valparaiso',null,'IN',null,null),
 ('435','Missouri Science and Technology','missouri-tech',null,'MO',null,null),
 ('87','Butler ','butler',null,'IN',null,null),
 ('1438','West Liberty State College','west-liberty-state-college',null,'',null,null),
 ('356','Lincoln  (Missouri)','lincoln-missouri',null,'MO',null,null),
 ('30049','Central State ','central-state',null,'',null,null),
 ('800','Wisconsin, Platteville','wisconsin-platteville',null,'WI',null,null),
 ('70','Bowie State ','bowie-state',null,'MD',null,null),
 ('181','Delta State ','delta-state',null,'',null,null),
 ('358','West Alabama','west-alabama',null,'AL',null,null),
 ('947','Arkansas Tech ','arkansas-tech',null,'AR',null,null),
 ('1289','Ouachita Baptist ','ouachita-baptist',null,'',null,null),
 ('561','Quincy ','quincy',null,'',null,null),
 ('1266','Northern State ','northern-state',null,'',null,null),
 ('275','Harvard ','harvard',null,'MA',null,null),
 ('167','Cornell ','cornell',null,'NY',null,null),
 ('263','Greensboro College','greensboro-college',null,'',null,null),
 ('1116','Harding ','harding',null,'',null,null),
 ('487','North Alabama','north-alabama',null,'AL',null,null),
 ('209','Edinboro','edinboro',null,'PA',null,null),
 ('143','Clarion Pennsylvania','clarion-of-pennsylvania',null,'PA',null,null),
 ('638','Shippensburg Pennsylvania','shippensburg-of-pennsylvania',null,'PA',null,null),
 ('339','Kutztown','kutztown',null,'PA','',''),
 ('423','Millersville','millersville-of-pennsylvania',null,'PA',null,null),
 ('197','East Stroudsburg','east-stroudsburg',null,'PA',null,null),
 ('135','Cheyney Pennsylvania','cheyney-of-pennsylvania',null,'PA',null,null),
 ('362','C.W. Post Campus/Long Island ','cw-post',null,'NY',null,null),
 ('593','Saint Anselm College','saint-anselm-college',null,'',null,null),
 ('81','Bryant ','bryant',null,'',null,null),
 ('22','American International College','american-international-college',null,'',null,null),
 ('410','Merrimack College','merrimack-college',null,'',null,null),
 ('533','Pace ','pace',null,'',null,null),
 ('384','Mansfield Pennsylvania','mansfield-of-pennsylvania',null,'PA',null,null),
 ('106','California Pennsylvania','california-of-pennsylvania',null,'PA',null,null),
 ('307','Indiana (Pa.)','indiana-of-pennsylvania',null,'PA',null,null),
 ('744','Virginia Union ','virginia-union',null,'VA',null,null),
 ('210','Elizabeth City State ','elizabeth-city-state',null,'NC',null,null),
 ('194','Duquesne ','duquesne',null,'PA',null,null),
 ('682','Stonehill College','stonehill-college',null,'',null,null),
 ('622','Salisbury ','salisbury',null,'',null,null),
 ('340','La Salle ','la-salle',null,'PA',null,null),
 ('259','Rowan ','rowan',null,'',null,null),
 ('565','Randolph-Macon College','randolph-macon-college',null,'VA',null,null),
 ('225','Ferrum College','ferrum-college',null,'',null,null),
 ('139','Christopher Newport ','christopher-newport',null,'',null,null),
 ('44','Averett ','averett',null,'',null,null),
 ('604','Saint Joseph\'s College (Indiana)','saint-josephs-college-indiana',null,'IN',null,null),
 ('12810','Northeastern State ','northeastern-state',null,'',null,null),
 ('155','Colorado School of Mines','colorado-school-of-mines',null,'CO',null,null),
 ('2814','Washburn Topeka','washburn-of-topeka',null,'KS',null,null),
 ('291','Humboldt State ','humboldt-state',null,'',null,null),
 ('2759','Western State CollegeColorado','western-state-college-of-colorado',null,'CO',null,null),
 ('359','Livingstone College','livingstone-college',null,'',null,null),
 ('9630','West Virginia Wesleyan College','west-virginia-wesleyan-college',null,'WV',null,null),
 ('496','North Park ','north-park',null,'',null,null),
 ('27854','Minnesota, Crookston','university-of-minnesota,-crookston',null,'MN',null,null),
 ('1240','Minnesota State  Moorhead','minnesota-state-moorhead',null,'MN',null,null),
 ('8736','Southwest Minnesota State ','southwest-minnesota-state',null,'MN',null,null),
 ('728','Upper Iowa ','upper-iowa',null,'IA',null,null),
 ('10870','Shepherd ','shepherd',null,'',null,null),
 ('405','Menlo College','menlo-college',null,'',null,null),
 ('134','Chapman ','chapman',null,'',null,null),
 ('770','Western Connecticut State ','western-connecticut-state',null,'CT',null,null),
 ('801','Wisconsin, River Falls','wisconsin-river-falls',null,'WI',null,null),
 ('54','Bemidji State ','bemidji-state',null,'',null,null),
 ('790','Winona State ','winona-state',null,'',null,null),
 ('491','North Carolina Wesleyan College','north-carolina-wesleyan-college',null,'NC',null,null),
 ('216','Emory and Henry College','emory-and-henry-college',null,'VA',null,null),
 ('396','Maryville College (Tennessee)','maryville-college-tennessee',null,'TN',null,null),
 ('637','Shenandoah ','shenandoah',null,'',null,null),
 ('1079','Findlay','university-of-findlay',null,'',null,null),
 ('280','Hillsdale College','hillsdale-college',null,'',null,null),
 ('246','Gannon ','gannon',null,'',null,null),
 ('1098','Glenville State College','glenville-state-college',null,'',null,null),
 ('1439','West Virginia State ','west-virginia-state',null,'WV',null,null),
 ('1076','Fairmont State ','fairmont-state',null,'WV',null,null),
 ('1222','Midwestern State ','midwestern-state',null,'',null,null),
 ('1009','Central Oklahoma','university-of-central-oklahoma',null,'OK',null,null),
 ('1371','Southeastern Oklahoma State ','southeastern-oklahoma-state',null,'OK',null,null),
 ('24342','Oklahoma Panhandle State ','oklahoma-panhandle-state',null,'OK',null,null),
 ('8965','East Central ','east-central',null,'',null,null),
 ('25','Angelo State ','angelo-state',null,'',null,null),
 ('224','Ferris State ','ferris-state',null,'',null,null),
 ('1433','Wayne State College (Nebraska)','wayne-state-college-nebraska',null,'NE',null,null),
 ('9013','Missouri Western State ','missouri-western-state',null,'MO',null,null),
 ('785','Willamette ','willamette',null,'',null,null),
 ('507','Northwest Missouri State ','northwest-missouri-state',null,'MO',null,null),
 ('9011','Fort Hays State ','fort-hays-state',null,'KS',null,null),
 ('130','Central Missouri','central-missouri',null,'MO',null,null),
 ('802','Wisconsin, Stevens Point','wisconsin-stevens-point',null,'WI',null,null),
 ('805','Wisconsin, Whitewater','wisconsin-whitewater',null,'WI',null,null),
 ('803','Wisconsin, Stout','wisconsin-stout',null,'WI',null,null),
 ('798','Wisconsin, Oshkosh','wisconsin-oshkosh',null,'WI',null,null),
 ('8911','Wisconsin Lutheran College','wisconsin-lutheran-college',null,'WI',null,null),
 ('42','Aurora ','aurora',null,'',null,null),
 ('15','Albion College','albion-college',null,'',null,null),
 ('192','Dubuque','dubuque',null,'IA',null,null),
 ('40','Augustana College (Illinois)','augustana-college-illinois',null,'IL',null,null),
 ('793','Wisconsin, Eau Claire','wisconsin-eau-claire',null,'WI',null,null),
 ('1314','Pittsburg State ','pittsburg-state',null,'KS',null,null),
 ('9012','Missouri Southern State ','missouri-southern-state',null,'MO',null,null),
 ('1112','Guilford College','guilford-college',null,'',null,null),
 ('2755','Southwest Baptist ','southwest-baptist',null,'',null,null),
 ('548','Plymouth State ','plymouth-state',null,'',null,null),
 ('26107','Becker College','becker-college',null,'',null,null),
 ('656','Massachusetts, Dartmouth','massachusetts-dartmouth',null,'MA',null,null),
 ('442','Montclair State ','montclair-state',null,'NJ',null,null),
 ('763','Wesley College','wesley-college',null,'',null,null),
 ('243','Frostburg State ','frostburg-state',null,'MD',null,null),
 ('730','Ursinus College','ursinus-college',null,'',null,null),
 ('124','Catholic ','catholic',null,'DC',null,null),
 ('712','The CollegeNew Jersey','the-college-of-new-jersey',null,'NJ',null,null),
 ('168','SUNY Cortland','suny-cortland',null,'NY',null,null),
 ('78','SUNY Brockport','suny-brockport',null,'NY',null,null),
 ('787','William Paterson New Jersey','william-paterson-of-new-jersey',null,'NJ',null,null),
 ('30075','Mary','university-of-mary',null,'',null,null),
 ('499','Truman State ','truman-state',null,'',null,null),
 ('1133','Husson College','husson-college',null,'',null,null),
 ('751','Washington and Jefferson College','washington-and-jefferson-college',null,'',null,null),
 ('85','Buffalo State College','buffalo-state-college',null,'',null,null),
 ('182','Denison ','denison',null,'',null,null),
 ('752','Washington and Lee ','washington-and-lee',null,'',null,null),
 ('773','McDaniel College','mcdaniel-college',null,'',null,null),
 ('269','Hampden-Sydney College','hampden-sydney-college',null,'',null,null),
 ('452','Mount Union College','mount-union-college',null,'',null,null),
 ('262','Grand Valley State ','grand-valley-state',null,'',null,null),
 ('309','Indianapolis','indianapolis',null,'IN',null,null),
 ('296','Benedictine  (Illinois)','benedictine-illinois',null,'IL',null,null),
 ('585','Rose-Hulman InstituteTechnology','rose-hulman-institute-of-technology',null,'',null,null),
 ('492','North Central College','north-central-college',null,'',null,null),
 ('424','Millikin ','millikin',null,'',null,null),
 ('778','Wheaton College (Illinois)','wheaton-college-illinois',null,'IL',null,null),
 ('300','Illinois Wesleyan ','illinois-wesleyan',null,'IL',null,null),
 ('212','Elmhurst College','elmhurst-college',null,'',null,null),
 ('161','Concordia College, Moorhead','concordia-college,-moorhead',null,'',null,null),
 ('8530','McMurry ','mcmurry',null,'',null,null),
 ('22235','Lewis &amp; Clark College','lewis-amp;-clark-college',null,'',null,null),
 ('1454','Whitworth ','whitworth',null,'',null,null),
 ('1179','Linfield College','linfield-college',null,'',null,null),
 ('376','Macalester College','macalester-college',null,'MN',null,null),
 ('567','Redlands','university-of-redlands',null,'',null,null),
 ('142','Claremont McKenna-Harvey Mudd-Scripps Colleges','claremont-mckenna-harvey-mudd-scripps-colleges',null,'CA',null,null),
 ('781','Whittier College','whittier-college',null,'CA',null,null),
 ('549','Pomona-Pitzer Colleges','pomona-pitzer-colleges',null,'',null,null),
 ('516','Occidental College','occidental-college',null,'',null,null),
 ('341','La Verne','university-of-la-verne',null,'',null,null),
 ('602','St. John\'s  (Minnesota)','st-johns-minnesota',null,'MN',null,null),
 ('385','Marietta College','marietta-college',null,'',null,null),
 ('75','Bridgewater College (Virginia)','bridgewater-college-virginia',null,'VA',null,null),
 ('1162','La Grange College','la-grange-college',null,'',null,null),
 ('652','University of the South','university-of-the-south',null,'',null,null),
 ('1434','Waynesburg ','waynesburg',null,null,null,null),
 ('510','Northwood  (Michigan)','northwood-michigan',null,'MI',null,null),
 ('757','Wayne State  (Michigan)','wayne-state-michigan',null,'MI',null,null),
 ('408','Mercyhurst College','mercyhurst-college',null,'PA',null,null),
 ('417','Michigan Technological ','michigan-technological',null,'MI',null,null),
 ('166','Cornell College','cornell-college',null,'NY',null,null),
 ('806','Wittenberg ','wittenberg',null,'',null,null),
 ('30037','Tri-State ','tri-state',null,'',null,null),
 ('286','Hope College','hope-college',null,'',null,null),
 ('525','Olivet College','olivet-college',null,'',null,null),
 ('4','Adrian College','adrian-college',null,'',null,null),
 ('35','Ashland ','ashland',null,'',null,null),
 ('591','Saginaw Valley State ','saginaw-valley-state',null,'',null,null),
 ('1071','Emporia State ','emporia-state',null,'KS',null,null),
 ('105','California Lutheran ','california-lutheran',null,'CA',null,null),
 ('1297','Pacific Lutheran ','pacific-lutheran',null,'',null,null),
 ('271','Hardin-Simmons ','hardin-simmons',null,'',null,null),
 ('1164','Lakeland College','lakeland-college',null,'',null,null),
 ('577','Ripon College','ripon-college',null,'',null,null),
 ('1036','Concordia  (Wisconsin)','concordia-wisconsin',null,'WI',null,null),
 ('326','Kalamazoo College','kalamazoo-college',null,'',null,null),
 ('582','Rockford College','rockford-college',null,'',null,null),
 ('377','MacMurray College','macmurray-college',null,'',null,null),
 ('1111','Greenville College','greenville-college',null,'',null,null),
 ('160','Concordia  Chicago','concordia-chicago',null,'IL',null,null),
 ('218','Eureka College','eureka-college',null,'',null,null),
 ('707','Thiel College','thiel-college',null,'PA',null,null),
 ('364','Loras College','loras-college',null,'',null,null),
 ('372','Luther College','luther-college',null,'',null,null),
 ('126','Central College (Iowa)','central-college-iowa',null,'IA',null,null),
 ('641','Simpson College','simpson-college',null,'',null,null),
 ('750','Wartburg College','wartburg-college',null,'',null,null),
 ('121','Carthage College','carthage-college',null,'',null,null),
 ('27901','Mount Ida College','mount-ida-college',null,'',null,null),
 ('775','Western New England College','western-new-england-college',null,'',null,null),
 ('8981','Endicott College','endicott-college',null,'',null,null),
 ('170','Curry College','curry-college',null,'',null,null),
 ('398','Massachusetts InstituteTechnology','massachusetts-institute-of-technology',null,'MA',null,null),
 ('623','Salve Regina ','salve-regina',null,'',null,null),
 ('733','Utica College','utica-college',null,'NY',null,null),
 ('808','Worcester Polytechnic Institute','worcester-polytechnic-institute',null,'',null,null),
 ('570','Rensselaer Polytechnic Institute','rensselaer-polytechnic-institute',null,'',null,null),
 ('273','Hartwick College','hartwick-college',null,'',null,null),
 ('478','State New York Maritime College','suny-maritime-college',null,'NY',null,null),
 ('76','Bridgewater State College','bridgewater-state-college',null,'',null,null),
 ('484','Nichols College','nichols-college',null,'',null,null),
 ('1130','Huntingdon College','huntingdon-college',null,'',null,null),
 ('1402','Thomas More College','thomas-more-college',null,'',null,null),
 ('1451','Westminster College (Pennsylvania)','westminster-college-pennsylvania',null,'PA',null,null),
 ('685','Susquehanna ','susquehanna',null,'',null,null),
 ('122','Case Western Reserve ','case-western-reserve',null,'OH',null,null),
 ('258','Gettysburg College','gettysburg-college',null,'PA',null,null),
 ('322','Johns Hopkins ','johns-hopkins',null,'',null,null),
 ('185','Dickinson College','dickinson-college',null,'',null,null),
 ('453','Muhlenberg College','muhlenberg-college',null,'PA',null,null),
 ('221','Fairleigh Dickinson , Florham','fairleigh-dickinson',null,'NJ',null,null),
 ('329','Kean ','kean',null,'',null,null),
 ('313','Ithaca College','ithaca-college',null,'NY',null,null),
 ('601','St. John Fisher College','st-john-fisher-college',null,'',null,null),
 ('784','Wilkes ','wilkes',null,'PA',null,null),
 ('282','Hobart College','hobart-college',null,'',null,null),
 ('1115','Hanover College','hanover-college',null,'',null,null),
 ('426','Millsaps College','millsaps-college',null,'',null,null),
 ('1062','East Texas Baptist ','east-texas-baptist',null,'TX',null,null),
 ('783','Widener ','widener',null,'PA',null,null),
 ('1203','Mary Hardin-Baylor','university-of-mary-hardin-baylor',null,'',null,null),
 ('557','Puget Sound','puget-sound',null,'WA',null,null),
 ('132','Centre College','centre-college',null,'',null,null),
 ('266','Gustavus Adolphus College','gustavus-adolphus-college',null,'',null,null),
 ('150','Coe College','coe-college',null,'',null,null),
 ('84','Buena Vista ','buena-vista',null,'',null,null),
 ('46','Baldwin-Wallace College','baldwin-wallace-college',null,'',null,null),
 ('722','U.S. Coast Guard Academy','coast-guard',null,'',null,null),
 ('378','Maine Maritime Academy','maine-maritime-academy',null,'ME',null,null),
 ('245','Gallaudet ','gallaudet',null,'DC',null,null),
 ('227','Fitchburg State College','fitchburg-state-college',null,'',null,null),
 ('673','Springfield College','springfield-college',null,'',null,null),
 ('16','Albright College','albright-college',null,'',null,null),
 ('239','Franklin &amp; Marshall College','franklin-amp;-marshall-college',null,'',null,null),
 ('520','Ohio Wesleyan ','ohio-wesleyan',null,'OH',null,null),
 ('511','Norwich ','norwich',null,'',null,null),
 ('18','Alfred ','alfred',null,'',null,null),
 ('19','Allegheny College','allegheny-college',null,'PA',null,null),
 ('515','Oberlin College','oberlin-college',null,'OH',null,null),
 ('265','Grove City College','grove-city-college',null,'',null,null),
 ('59','Bethany College (West Virginia)','bethany-college-west-virginia',null,'WV',null,null),
 ('281','Hiram College','hiram-college',null,'',null,null),
 ('335','Kenyon College','kenyon-college',null,'',null,null),
 ('747','Wabash College','wabash-college',null,'',null,null),
 ('195','Earlham College','earlham-college',null,'',null,null),
 ('531','Otterbein College','otterbein-college',null,'',null,null),
 ('455','Muskingum College','muskingum-college',null,'',null,null),
 ('278','Heidelberg College','heidelberg-college',null,'',null,null),
 ('517','Ohio Northern ','ohio-northern',null,'OH',null,null),
 ('1461','Wilmington College (Ohio)','wilmington-college-ohio',null,'OH',null,null),
 ('117','Capital ','capital',null,'',null,null),
 ('320','John Carroll ','john-carroll',null,'',null,null),
 ('8567','Mount St. Joseph','college-of-mount-st-joseph',null,'',null,null),
 ('1050','Defiance College','defiance-college',null,'',null,null),
 ('987','Bluffton ','bluffton',null,'',null,null),
 ('2694','Franklin College','franklin-college',null,'',null,null),
 ('939','Anderson  (Indiana)','anderson-indiana',null,'IN',null,null),
 ('1192','Manchester College','manchester-college',null,'',null,null),
 ('755','Washington  (Missouri)','washington-missouri',null,'MO',null,null),
 ('297','Illinois College','illinois-college',null,'IL',null,null),
 ('137','Chicago','university-of-chicago',null,'IL',null,null),
 ('60','Bethel  (Minnesota)','bethel-minnesota',null,'MN',null,null),
 ('38','Augsburg College','augsburg-college',null,'',null,null),
 ('268','Hamline ','hamline',null,'',null,null),
 ('615','St. Olaf College','st-olaf-college',null,'MN',null,null),
 ('620','St. Thomas (Minnesota)','st-thomas',null,'MN',null,null),
 ('118','Carleton College','carleton-college',null,'',null,null),
 ('1226','Minnesota, Morris','university-of-minnesota,-morris',null,'MN',null,null),
 ('953','Austin College','austin-college',null,'',null,null),
 ('1182','Louisiana College','louisiana-college',null,'LA',null,null),
 ('429','Mississippi College','mississippi-college',null,'MS',null,null),
 ('2741','Howard Payne ','howard-payne',null,'',null,null),
 ('1390','Sul Ross State ','sul-ross-state',null,'',null,null),
 ('1400','Texas Lutheran ','texas-lutheran',null,'TX',null,null),
 ('154','Colorado College','colorado-college',null,'CO',null,null),
 ('53','Beloit College','beloit-college',null,'',null,null),
 ('555','Principia College','principia-college',null,'',null,null),
 ('30035','Crown College (MN)','crown-college-mn',null,'MN',null,null),
 ('715','Trinity  (Texas)','trinity-texas',null,'TX',null,null),
 ('177','DePauw ','depauw',null,'IN',null,null),
 ('573','Rhodes College','rhodes-college',null,'',null,null),
 ('807','Wooster','wooster',null,'OH',null,null),
 ('30031','Northwestern College','northwestern-college',null,'',null,null),
 ('344','Lake Forest College','lake-forest-college',null,'',null,null),
 ('337','Knox College','knox-college',null,'',null,null),
 ('120','Carroll College (Wisconsin)','carroll-college-wisconsin',null,'WI',null,null),
 ('438','Monmouth College (Illinois)','monmouth-college-illinois',null,'IL',null,null),
 ('614','St. Norbert College','st-norbert-college',null,'',null,null),
 ('264','Grinnell College','grinnell-college',null,'IA',null,null),
 ('348','Lawrence ','lawrence',null,'',null,null),
 ('1194','Maranatha Baptist Bible College','maranatha-baptist-bible-college',null,'',null,null),
 ('1450','Westminster College (Missouri)','westminster-college-missouri',null,'MO',null,null),
 ('64','Blackburn College','blackburn-college',null,'',null,null),
 ('8597','Martin Luther College','martin-luther-college',null,'',null,null),
 ('119','Carnegie Mellon ','carnegie-mellon',null,'PA',null,null),
 ('777','Westfield State College','westfield-state-college',null,'',null,null),
 ('399','Massachusetts Maritime Academy','massachusetts-maritime-academy',null,'MA',null,null),
 ('809','Worcester State College','worcester-state-college',null,'',null,null),
 ('238','Framingham State College','framingham-state-college',null,'',null,null),
 ('724','U.S. Merchant Marine Academy','merchant-marine-academy',null,'',null,null),
 ('727','Union College (New York)','union-college-new-york',null,'NY',null,null),
 ('581','Rochester','rochester',null,'NY',null,null),
 ('607','St. Lawrence ','st-lawrence',null,'',null,null),
 ('443','Moravian College','moravian-college',null,'',null,null),
 ('336','King\'s College (Pennsylvania)','kings-college-pennsylvania',null,'PA',null,null),
 ('325','Juniata College','juniata-college',null,'',null,null),
 ('179','Delaware Valley College','delaware-valley-college',null,'DE',null,null),
 ('373','Lycoming College','lycoming-college',null,'PA',null,null),
 ('351','Lebanon Valley College','lebanon-valley-college',null,'',null,null),
 ('5','Akron','akron','9','OH','http://www.gozips.com/SportSelect.dbml?DB_OEM_ID=10800&KEY=&SPID=4319&SPSID=47122',null),
 ('30','Arkansas State ','arkansas-state','10','AR',null,null),
 ('47','Ball State ','ball-state','9','IN',null,null),
 ('66','Boise State ','boise-state','8','ID',null,null),
 ('71','Bowling Green State ','bowling-green','9','OH',null,null),
 ('77','Brigham Young ','byu','11','UT',null,null),
 ('86','Buffalo','buffalo','9','NY',null,null),
 ('96','Fresno State','fresno-state',null,'CA',null,null),
 ('128','Central Florida','central-florida','6','FL',null,null),
 ('156','Colorado State ','colorado-state','11','CO',null,null),
 ('204','Eastern Michigan ','eastern-michigan','9','MI',null,null),
 ('277','Hawaii','hawaii',null,null,null,null),
 ('288','Houston','houston','6','TX',null,null),
 ('295','Idaho','idaho','8','ID',null,null),
 ('331','Kent','kent-state','9','OH',null,null),
 ('366','Louisiana Tech ','louisiana-tech',null,'LA',null,null),
 ('388','Marshall ','marshall','6','WV',null,null),
 ('404','Memphis','memphis','6','TN',null,null),
 ('414','Miami (Ohio)','miami-ohio','9','OH',null,null),
 ('419','Middle Tennessee State ','middle-tennessee-state','10','TN',null,null),
 ('463','Nebraska','nebraska','7','NE',null,null),
 ('465','Nevada-Las Vegas','unlv','11','NV',null,null),
 ('466','Nevada','nevada',null,'NV',null,null),
 ('472','New Mexico State ','new-mexico-state',null,'NM',null,null),
 ('473','New Mexico','new-mexico','11','NM',null,null),
 ('497','North Texas','north-texas','10','TX',null,null),
 ('498','Louisiana-Monroe','louisiana-monroe','10','LA',null,null),
 ('503','Northern Illinois ','northern-illinois','9','IL',null,null),
 ('513','Notre Dame','notre-dame','12','IN',null,null),
 ('519','Ohio ','ohio','9','OH',null,null),
 ('626','San Diego State ','san-diego-state','11','CA',null,null),
 ('630','San Jose State ','san-jose-state','8','CA',null,null),
 ('663','Southern Methodist ','southern-methodist','6','TX',null,null),
 ('664','Southern Mississippi','southern-mississippi','6','MS',null,null),
 ('671','Louisiana-Lafayette','louisiana-lafayette','10','LA',null,null),
 ('690','Temple ','temple','12','PA',null,null),
 ('698','Texas Christian ','texas-christian','11','TX',null,null),
 ('700','Texas Tech ','texas-tech',null,'TX',null,null),
 ('704','Texas-El Paso','utep','6','TX',null,null),
 ('709','Toledo','toledo','9','OH',null,null),
 ('716','Troy ','troy','10','AL',null,null),
 ('718','Tulane ','tulane','6','LA',null,null),
 ('719','Tulsa','tulsa','6','OK',null,null),
 ('721','Air Force','air-force','11','CO','http://goairforcefalcons.cstv.com/sports/m-footbl/afa-m-footbl-body.html',null),
 ('725','Army','army','12','NY',null,null),
 ('731','Utah State ','utah-state',null,'UT',null,null),
 ('732','Utah','utah','11','UT',null,null),
 ('772','Western Kentucky ','western-kentucky',null,'KY',null,null),
 ('774','Western Michigan ','western-michigan','9','MI',null,null),
 ('811','Wyoming','wyoming','11','WY',null,null),
 ('769','Western Carolina ','western-carolina',null,'SC',null,null),
 ('17','Alcorn State ','alcorn-state',null,null,null,null),
 ('501','Northern Arizona ','northern-arizona',null,'AZ',null,null),
 ('693','Tennessee-Chattanooga','tennessee-chattanooga',null,'TN',null,null),
 ('692','Tennessee Tech','tennessee-tech',null,'TN',null,null),
 ('670','Texas State','texas-state',null,'TX',null,null),
 ('758','Weber State ','weber-state',null,null,null,null),
 ('400','Massachusetts','massachusetts',null,'MA',null,null),
 ('207','Eastern Washington ','eastern-washington',null,'WA',null,null),
 ('102','Sacramento State','sacrament-state',null,'CA','',''),
 ('493','North Dakota State ','north-dakota-state',null,'ND',null,null),
 ('654','Southeast Missouri State ','southeast-missouri-state',null,'MO',null,null),
 ('244','Furman ','furman',null,null,null,null),
 ('253','Georgia Southern ','georgia-southern',null,'GA',null,null),
 ('380','Maine','maine',null,'ME',null,null),
 ('290','Howard ','howard',null,'DC',null,null),
 ('625','Samford ','samford',null,null,null,null),
 ('502','Northern Colorado','northern-colorado',null,'CO',null,null),
 ('699','Texas Southern ','texas-southern',null,'TX',null,null),
 ('90','California Polytechnic State ','cal-poly',null,'CA',null,null),
 ('771','Western Illinois ','western-illinois',null,'IL',null,null),
 ('305','Indiana State ','indiana-state',null,'IN',null,null),
 ('504','Northern Iowa','northern-iowa',null,'IA',null,null),
 ('669','Missouri State ','missouri-state',null,'MO',null,null),
 ('655','Southeast Louisiana ','southeast-louisiana',null,'LA','',''),
 ('178','Delaware State ','delaware-state',null,'DE',null,null),
 ('202','Eastern Kentucky ','eastern-kentucky',null,'KY',null,null),
 ('454','Murray State ','murray-state',null,null,null,null),
 ('469','New Hampshire','new-hampshire',null,'NH',null,null),
 ('739','Villanova ','villanova',null,'PA',null,null),
 ('315','Jacksonville State ','jacksonville-state',null,null,null,null),
 ('27','Appalachian State ','appalachian-state',null,null,null,null),
 ('1092','Gardner-Webb ','',null,null,null,null),
 ('508','Northwestern State ','northwestern-state',null,null,null,null),
 ('299','Illinois State ','illinois-state',null,'IL',null,null),
 ('317','James Madison ','james-madison',null,null,null,null),
 ('483','Nicholls State ','nicholls-state',null,null,null,null),
 ('2915','Wofford','wofford',null,null,null,null),
 ('261','Grambling State ','grambling-state',null,null,null,null),
 ('659','Southern Illinois','southern-illinois',null,'IL',null,null),
 ('500','Northeastern ','northeastern',null,'MA',null,null),
 ('817','Youngstown State ','youngstown-state',null,'OH',null,null),
 ('624','Sam Houston State ','sam-houston-state',null,'TX',null,null),
 ('294','Idaho State ','idaho-state',null,'ID',null,null),
 ('201','Eastern Illinois ','eastern-illinois',null,'IL',null,null),
 ('485','Norfolk State ','norfolk-state',null,null,null,null),
 ('550','Portland State ','portland-state',null,null,null,null),
 ('108','California-Davis','california-davis',null,'CA',null,null),
 ('647','South Carolina State ','south-carolina-state',null,'SC',null,null),
 ('695','Tennessee-Martin','tennessee-martin',null,'TN',null,null),
 ('402','McNeese State ','mcneese-state',null,null,null,null),
 ('440','Montana State','montana-state',null,'MT',null,null),
 ('355','Liberty ','liberty',null,null,null,null),
 ('572','Rhode Island','rhode-island',null,'RI',null,null),
 ('180','Delaware','delaware',null,'DE',null,null),
 ('575','Richmond','richmond',null,'VA',null,null),
 ('786','William & Mary','william-mary',null,'VA',null,null),
 ('444','Morehead State ','morehead-state',null,null,null,null),
 ('14901','West Va. Tech','west-va-tech',null,'WV',null,null),
 ('127','Central Connecticut State ','central-connecticut-state',null,null,null,null),
 ('141','Citadel','citadel',null,'SC',null,null),
 ('8','Alabama','alabama','1','AL','http://www.rolltide.com/SportSelect.dbml?&DB_OEM_ID=8000&KEY=&SPID=3011&SPSID=37423',null),
 ('29','Arizona','arizona','4','AZ','http://www.arizonaathletics.com/SportSelect.dbml?DB_OEM_ID=1600&KEY=&SPID=516&SPSID=8107',null),
 ('28','Arizona State ','arizona-state','4','AZ','http://thesundevils.cstv.com/sports/m-footbl/asu-m-footbl-body.html',null),
 ('37','Auburn ','auburn','1','AL','http://auburntigers.cstv.com/sports/m-footbl/aub-m-footbl-body.html',null),
 ('31','Arkansas','arkansas','1','AR',null,null),
 ('51','Baylor ','baylor','7','TX',null,null),
 ('67','Boston College','boston-college','2','MA',null,null),
 ('107','California','california','4','CA',null,null),
 ('140','Cincinnati','cincinnati','3','OH',null,null),
 ('147','Clemson ','clemson','2','SC',null,null),
 ('157','Colorado','colorado','7','CO',null,null),
 ('164','Connecticut','connecticut','3','CT',null,null),
 ('193','Duke ','duke','2','NC',null,null),
 ('235','Florida','florida','1','FL',null,null),
 ('234','Florida State ','florida-state','2','FL',null,null),
 ('257','Georgia','georgia','1','GA',null,null),
 ('255','Georgia Tech','georgia-tech','2','GA',null,null),
 ('301','Illinois','illinois','5','IL',null,null),
 ('306','Indiana','indiana','5','IN',null,null),
 ('312','Iowa','iowa','5','IA',null,null),
 ('311','Iowa State ','iowa-state','7','IA',null,null),
 ('328','Kansas','kansas','7','KS',null,null),
 ('327','Kansas State ','kansas-state','7','KS',null,null),
 ('334','Kentucky','kentucky','1','KY',null,null),
 ('365','Louisiana State','lsu','1','LA',null,null),
 ('367','Louisville','louisville','3','KY',null,null),
 ('392','Maryland','maryland','2','MD',null,null),
 ('415','Miami (Florida)','miami','2','FL',null,null),
 ('418','Michigan','michigan','5','MI',null,null),
 ('416','Michigan State ','michigan-state','5','MI',null,null),
 ('428','Minnesota','minnesota','5','MN',null,null),
 ('433','Mississippi','mississippi','1','MS',null,null),
 ('430','Mississippi State ','mississippi-state','1','MS',null,null),
 ('434','Missouri','missouri','7','MO',null,null),
 ('457','North Carolina','north-carolina','2','NC',null,null),
 ('490','North Carolina State ','north-carolina-state','2','NC',null,null),
 ('509','Northwestern ','northwestern','5','IL',null,null),
 ('518','Ohio State ','ohio-state','5','OH',null,null),
 ('522','Oklahoma','oklahoma','7','OK',null,null),
 ('521','Oklahoma State ','oklahoma-state','7','OK',null,null),
 ('529','Oregon','oregon','4','OR',null,null),
 ('528','Oregon State ','oregon-state','4','OR',null,null),
 ('539','Penn State','penn-state','5','PA',null,null),
 ('545','Pittsburgh','pittsburgh','3','PA',null,null),
 ('559','Purdue ','purdue','5','IN',null,null),
 ('574','Rice ','rice','6','TX',null,null),
 ('587','Rutgers','rutgers','3','NJ',null,null),
 ('648','South Carolina','south-carolina','1','SC',null,null),
 ('651','South Florida','south-florida','3','FL',null,null),
 ('657','Southern California','southern-cal','4','CA',null,null),
 ('674','Stanford ','stanford','4','CA',null,null),
 ('688','Syracuse ','syracuse','3','NY',null,null),
 ('694','Tennessee','tennessee','1','TN',null,null),
 ('703','Texas','texas','7','TX',null,null),
 ('697','Texas A&M','texas-am','7','TX',null,null),
 ('110','UCLA','ucla','4','CA',null,null),
 ('736','Vanderbilt ','vanderbilt','1','TN',null,null),
 ('746','Virginia','virginia','2','VA',null,null),
 ('742','Virginia Tech','virginia-tech','2','VA',null,null),
 ('749','Wake Forest ','wake-forest','2','NC',null,null),
 ('756','Washington','washington','4','WA',null,null),
 ('754','Washington State ','washington-state','4','WA',null,null),
 ('768','West Virginia ','west-virginia','3','WV',null,null),
 ('796','Wisconsin','wisconsin','5','WI',null,null),
 ('6','Alabama A&M ','alabama-am',null,'AL',null,null),
 ('2678','Arkansas-Pine Bluff','arkansas-pine-bluff',null,'AR',null,null),
 ('1004','Central Arkansas','central-arkansas',null,'AR',null,null),
 ('129','Central Michigan ','central-michigan','9','MI',null,null),
 ('48','Charleston Southern ','charleston-southern',null,null,null,null),
 ('228','Florida A&M ','florida-am',null,'FL',null,null),
 ('231','Florida International ','florida-international','10','FL',null,null),
 ('196','East Carolina ','east-carolina','6','NC',null,null),
 ('229','Florida Atlantic ','florida-atlantic','10','FL',null,null),
 ('30077','Wagner College','wagner-college',null,'NY',null,null),
 ('30094','Brevard College','',null,null,null,null),
 ('537','North Carolina at Pembroke','north-carolina-pembroke',null,'NC',null,null),
 ('248','George Mason ','george-mason',null,null,null,null),
 ('30063','Seton Hill ','',null,null,null,null),
 ('30095','Dixie State College','dixie-state',null,'UT',null,null),
 ('30084','Geneva College','geneva',null,null,null,null),
 ('30067','SUNY Morrisville','suny-morrisville',null,'NY',null,null),
 ('30064','Saint Vincent College','',null,null,null,null),
 ('28593','Birmingham-Southern College','',null,null,null,null),
 ('1340','St. Joseph\'s College (Long Island)','',null,null,null,null),
 ('254','Georgia State ','georgia-state',null,'GA',null,null),
 ('639','Siena College','siena',null,null,null,null),
 ('198','East Tennessee State ','east-tennessee-state',null,null,null,null),
 ('610','St. Mary\'s','st-marys',null,'CA','',''),
 ('470','New Haven','new-haven',null,null,null,null),
 ('603','St. John\'s  (New York)','st-johns-new-york',null,'NY',null,null),
 ('116','Canisius College','canisius',null,null,null,null),
 ('220','Fairfield ','fairfield',null,null,null,null),
 ('368','Massachusetts at Lowell','massachusetts-lowell',null,'MA',null,null),
 ('319','New Jersey City ','new-jersey-city',null,'NJ',null,null),
 ('462','Nebraska Wesleyan ','nebraska-wesleyan',null,'NE',null,null),
 ('101','Northridge State','cal-state-northridge',null,'CA',null,null),
 ('401','Massachusetts, Boston','massachusetts-boston',null,'MA',null,null),
 ('686','Swarthmore College','swarthmore-college',null,null,null,null),
 ('68','Boston ','boston',null,'MA',null,null),
 ('219','Evansville','evansville',null,'IN',null,null),
 ('1165','Lambuth ','',null,null,null,null),
 ('30096','Pacific','pacific',null,'CA','',''),
 ('30097','Fullerton State','fullerton-state',null,'CA','',''),
 ('30098','Long Beach State','long-beach-state',null,'CA','',''),
 ('30099','Cal Poly-San Luis Obispo','cal-poly-san-luis-obispo',null,'CA','',''),
 ('30100','Lamar','lamar',null,null,'',''),
 ('30101','Sonoma State','sonoma-state',null,'CA','',''),
 ('30102','West Virginia Tech','west-virginia-tech',null,'WV','',''),
 ('30103','Edward Waters','edward-waters',null,null,'','');

SET FOREIGN_KEY_CHECKS = 1;
