TRUNCATE college_collegetotal;
INSERT INTO college_collegetotal
SELECT  college_gameoffense.team_id,
    college_gameoffense.year,
    SUM(college_gameoffense.third_down_attempts),
    SUM(college_gameoffense.third_down_conversions),
    SUM(college_gameoffense.fourth_down_attempts),
    SUM(college_gameoffense.fourth_down_conversions),
    SUM(college_gameoffense.first_downs_rushing),
    SUM(college_gameoffense.first_downs_passing),
    SUM(college_gameoffense.first_downs_penalty),
    SUM(college_gameoffense.first_downs_total),
    SUM(college_gameoffense.penalties),
    SUM(college_gameoffense.penalty_yards),
    SUM(college_gameoffense.fumbles),
    SUM(college_gameoffense.fumbles),
    SUM(college_gameoffense.rushes),
    SUM(college_gameoffense.rush_gain),
    SUM(college_gameoffense.rush_loss),
    SUM(college_gameoffense.rush_net),
    SUM(college_gameoffense.rush_touchdowns),
    SUM(college_gameoffense.total_plays),
    SUM(college_gameoffense.total_yards),
    SUM(college_gameoffense.pass_attempts),
    SUM(college_gameoffense.pass_completions),
    SUM(college_gameoffense.pass_interceptions),
    SUM(college_gameoffense.pass_yards),
    SUM(college_gameoffense.pass_touchdowns),
    SUM(college_gameoffense.receptions),
    SUM(college_gameoffense.receiving_yards),
    SUM(college_gameoffense.receiving_touchdowns),
    SUM(college_gameoffense.punts),
    SUM(college_gameoffense.punt_yards),
    SUM(college_gameoffense.punt_returns),
    SUM(college_gameoffense.punt_return_yards),
    SUM(college_gameoffense.punt_return_touchdowns),
    SUM(college_gameoffense.kickoff_returns),
    SUM(college_gameoffense.kickoff_return_yards),
    SUM(college_gameoffense.kickoff_return_touchdowns),
    SUM(college_gameoffense.touchdowns),
    SUM(college_gameoffense.pat_attempts),
    SUM(college_gameoffense.pat_made),
    SUM(college_gameoffense.two_point_conversion_attempts),
    SUM(college_gameoffense.two_point_conversions),
    SUM(college_gameoffense.field_goal_attempts),
    SUM(college_gameoffense.field_goals_made),
    SUM(college_gameoffense.points)
FROM college_gameoffense, college_collegeyear
WHERE college_collegeyear.college_id = college_gameoffense.team_id AND college_collegeyear.season = college_gameoffense.year
GROUP BY college_gameoffense.team_id, college_gameoffense.year;